// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8URDvfmwY8LQ-lpZYbMx7IWBCZFw4yk',
    appId: '1:72635706914:web:f9bb060d21759ab9b0a47b',
    messagingSenderId: '72635706914',
    projectId: 'atividade-pdm-eed49',
    authDomain: 'atividade-pdm-eed49.firebaseapp.com',
    storageBucket: 'atividade-pdm-eed49.appspot.com',
    measurementId: 'G-119XRDYYVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPGgslBY46nNBAjjNwpZ-VfehwXVHI3w',
    appId: '1:72635706914:android:4eb9d143b0131f14b0a47b',
    messagingSenderId: '72635706914',
    projectId: 'atividade-pdm-eed49',
    storageBucket: 'atividade-pdm-eed49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGL8xXgYkT9qFnZWA9BylCxDAi7-pm3Bo',
    appId: '1:72635706914:ios:037e0d34dd0237c8b0a47b',
    messagingSenderId: '72635706914',
    projectId: 'atividade-pdm-eed49',
    storageBucket: 'atividade-pdm-eed49.appspot.com',
    iosClientId: '72635706914-qi9jr91jqq3ucrrh4n2ibnltdp5bp1ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.aulaPdm',
  );
}
